MaxDeath: 10 # Max amount of deaths before the module will start to verify join-permission
Messages:
  BannedMessage: '&4Your trial has finished! &2Contact an Admin to get full access'
  KickMessage: '&4Your trial has ended. &2Contact an Admin to get full access'
  TrialWarning: 'This was death %d. Your trial ends if you reach %d'
NumRanks: 5
Rank_0_Cost: 0
Rank_1_Cost: 20000
Rank_2_Cost: 50000
Rank_3_Cost: 75000
Rank_4_Cost: 100000
Rank_0_Name: "newbie"
Rank_1_Name: "dweller"
Rank_2_Name: "rank2"
Rank_3_Name: "rank3"
Rank_4_Name: "rank4"