NumRanks: 6
Rank_0_Cost: 0
Rank_1_Cost: 20000
Rank_2_Cost: 50000
Rank_3_Cost: 75000
Rank_4_Cost: 100000
Rank_5_Cost: 20000000
Rank_0_Name: newbie
Rank_1_Name: dweller
Rank_2_Name: villager
Rank_3_Name: resident
Rank_4_Name: citizen
Rank_5_Name: elite
MySQL_Host: localhost
MySQL_Port: 3306
MySQL_Database: database
MySQL_User: user
MySQL_Password: password
ServerID: set_server_id