# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout mod repo
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'zulu'
        cache: maven

    - name: Obtain version
      id: obtain-version
      run: |
        echo "version=$(git describe --tags)" >> "$GITHUB_OUTPUT"

    - name: Compile
      run: mvn -B package "-Drevision=${{ steps.obtain-version.outputs.version }}" --file pom.xml

    - name: Attach compilation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NewHorizonsServerCore-${{ steps.obtain-version.outputs.version }}.jar
        path: target/*.jar
        retention-days: 31
